name: Docker images

on:
  push:
  pull_request:

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['centos', 'clang', 'debian', 'fedora', 'opensuse', 'rocm',
                'ubuntu-18.04', 'ubuntu-20.04',
                'ubuntu-cuda-10.1', 'ubuntu-cuda-9.0',
                'ubuntu-travis', 'ubuntu-wo-dependencies']
    steps:
    - uses: actions/checkout@master
    - name: Build and deploy
      uses: ./.github/actions/docker
      with:
        image: ${{ matrix.image }}
        repository: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
        event_name: ${{ github.event_name }}
        tag: ${{ github.sha }}
        dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
  images-latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['fedora', 'rocm']
    steps:
    - uses: actions/checkout@master
    - name: Build and deploy
      uses: ./.github/actions/docker
      with:
        image: ${{ matrix.image }}
        repository: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
        event_name: ${{ github.event_name }}
        tag: "latest_base"
        dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
        dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
        build_args: "BASE_VERSION=latest"
